global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'orderer'
    static_configs:
      - targets: ['orderer.node.connection:9443']
  - job_name: 'peer0_registry'
    static_configs:
      - targets: ['peer0.registry.node.connection:9444']
  - job_name: 'peer0_viewer'
    static_configs:
      - targets: ['peer0.viewer.node.connection:9445']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
